/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.screens;

import javax.swing.JOptionPane;
import org.itson.domaincomponent.domain.Player;

/**
 *
 * @author paulvazquez
 */
public class frmHome extends javax.swing.JFrame {

    private static frmHome homeInstance;
    Player player;

    /**
     * Creates new form frmHome
     */
    private frmHome() {
        initComponents();
        this.player = getPlayer(); // Asignar el objeto Player recibido

    }

    private void closeCurrentWindow() {
        this.setVisible(false);
    }

    public static frmHome getInstance() {
        if (homeInstance == null) {
            homeInstance = new frmHome();
        }
        return homeInstance;
    }

    public void resetPlayer() {
        this.player = null;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    public Player getPlayer() {
        if (player != null) {
            return player;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnJoin = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lbNmatch = new javax.swing.JLabel();
        lbPlayersQuantity = new javax.swing.JLabel();
        lbGameStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/btnUnirse.jpg"))); // NOI18N
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        jPanel2.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 320, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/btnRegresar.jpg"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 250, 60));

        lbNmatch.setBackground(new java.awt.Color(255, 255, 255));
        lbNmatch.setFont(new java.awt.Font(".SF NS Text", 0, 18)); // NOI18N
        lbNmatch.setForeground(new java.awt.Color(255, 255, 255));
        lbNmatch.setText("Numero");
        jPanel2.add(lbNmatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 30));

        lbPlayersQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lbPlayersQuantity.setFont(new java.awt.Font(".SF NS Text", 0, 18)); // NOI18N
        lbPlayersQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lbPlayersQuantity.setText("Cantidad");
        jPanel2.add(lbPlayersQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 110, 30));

        lbGameStatus.setFont(new java.awt.Font(".SF NS Text", 0, 18)); // NOI18N
        lbGameStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbGameStatus.setText("Estado");
        jPanel2.add(lbGameStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 130, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/lbBuscar.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/infoPartida.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/tablaInfo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/fondo.jpeg"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed

        this.setVisible(false);
        frmLobby.getInstance().setVisible(true);
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        frmAvatarSelection.getInstance().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbGameStatus;
    private javax.swing.JLabel lbNmatch;
    private javax.swing.JLabel lbPlayersQuantity;
    // End of variables declaration//GEN-END:variables
}
