/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.screens;

import org.itson.classes.Lobby;
import org.itson.classes.DomainMatch;
import org.itson.domaincomponent.domain.Player;

/**
 *
 * @author Paul Alejandro Vazquez Cervantes
 * @author Santiago Leyva Bojorquez
 */
public class frmLobby extends javax.swing.JFrame {
        private static frmLobby lobbyInstance;
        Lobby matchClass = new Lobby();
        
    /**
     * Creates new form frmLobby
     */
    private frmLobby() {
        initComponents();
    }
    
    private void closeCurrentWindow(){
        this.setVisible(false);
    }
    
    public static frmLobby getInstance(){
        if (lobbyInstance == null){
            lobbyInstance = new frmLobby();
        }
        return lobbyInstance;
    }
    
    public void getPlayersData(){
        
    }
    
    public void notifyPlayers(){
        
    }
    
    public boolean acceptMatch(){
        return false;
    }
    
    public void dealTiles(){
       // matchClass.dealTiles();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLobby = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlayers = new javax.swing.JTextArea();
        lbTable = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLobby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobby/sala.jpeg"))); // NOI18N
        getContentPane().add(lbLobby, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        txtPlayers.setBackground(new java.awt.Color(255, 255, 255));
        txtPlayers.setColumns(20);
        txtPlayers.setRows(5);
        jScrollPane1.setViewportView(txtPlayers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, 130));

        lbTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobby/tablaInfo.jpeg"))); // NOI18N
        getContentPane().add(lbTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobby/btnVolver.jpeg"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        btnReady.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobby/btnListo.jpeg"))); // NOI18N
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });
        getContentPane().add(btnReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobby/fondo.jpeg"))); // NOI18N
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        frmHome.getInstance().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmMatch.getInstance().setVisible(true);
    }//GEN-LAST:event_btnReadyActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReady;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbLobby;
    private javax.swing.JLabel lbTable;
    private javax.swing.JTextArea txtPlayers;
    // End of variables declaration//GEN-END:variables
}
